version: "3.8"
services:
  web:
    build: ./
    command: gunicorn inboxiq_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
  celery:
    build: ./
    command: celery -A inboxiq_project worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:7
    ports:
      - "6380:6379"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inboxiq
      MYSQL_USER: inboxiq
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
