[build]
cmd = "cd inboxiq_project && python manage.py collectstatic --noinput && python manage.py migrate"

[deploy]
startCommand = "cd inboxiq_project && gunicorn inboxiq_project.wsgi:application --bind 0.0.0.0:$PORT"

[env]
PYTHONPATH = "/app/inboxiq_project"
